const fs = require('fs');
const file = 'd:\\antigravity\\Gamification\\Places_In_Town_Game.html';
let content = fs.readFileSync(file, 'utf8');

const newVocab = `const allVocab = [
    // --- NOUNS ---
    { word: "intersection", cat: "noun", ipa: "ˌɪntərˈsekʃn", vi: "ngã tư, giao lộ", eng: "A place where two or more roads cross each other.", icon: "🚦" },
    { word: "pharmacy", cat: "noun", ipa: "ˈfɑːrməsi", vi: "nhà thuốc", eng: "A shop where medicines are prepared and sold.", icon: "💊" },
    { word: "post office", cat: "noun", ipa: "ˈpoʊst ˌɒfɪs", vi: "bưu điện", eng: "A place where you can send letters and parcels.", icon: "📮" },
    { word: "bookstore", cat: "noun", ipa: "ˈbʊkstɔːr", vi: "hiệu sách", eng: "A shop where books are sold.", icon: "📚" },
    { word: "temple", cat: "noun", ipa: "ˈtempl", vi: "đền / chùa", eng: "A building used for the worship of a god or gods.", icon: "🛕" },
    { word: "neighborhood", cat: "noun", ipa: "ˈneɪbərˌhʊd", vi: "khu phố", eng: "A district or area within a town where people live.", icon: "🏡" },
    { word: "roundabout", cat: "noun", ipa: "ˈraʊndəbaʊt", vi: "vòng xuyến", eng: "A road junction where traffic moves in a circle.", icon: "🔄" },
    { word: "beach", cat: "noun", ipa: "biːtʃ", vi: "bãi biển", eng: "A sandy shore by the ocean.", icon: "🏖️" },
    { word: "alley", cat: "noun", ipa: "ˈæli", vi: "hẻm, ngõ", eng: "A narrow passage behind or between buildings.", icon: "🛣️" },
    { word: "convenience store", cat: "noun", ipa: "kənˈviːniəns stɔːr", vi: "cửa hàng tiện lợi", eng: "A small shop open long hours selling food and necessities.", icon: "🏪" },
    { word: "crosswalk", cat: "noun", ipa: "ˈkrɒswɔːk", vi: "vạch sang đường", eng: "A marked place where pedestrians can safely cross a road.", icon: "🦓" },
    { word: "traffic light", cat: "noun", ipa: "ˈtræfɪk laɪt", vi: "đèn giao thông", eng: "A set of colored lights controlling traffic.", icon: "🚥" },
    { word: "tourist", cat: "noun", ipa: "ˈtʊərɪst", vi: "du khách", eng: "A person visiting a place for pleasure.", icon: "📸" },
    { word: "pedestrian", cat: "noun", ipa: "pəˈdestriən", vi: "người đi bộ", eng: "A person walking in a street or public place.", icon: "🚶" },
    { word: "hospital", cat: "noun", ipa: "ˈhɒspɪtl", vi: "bệnh viện", eng: "A place for medical treatment.", icon: "🏥" },
    { word: "library", cat: "noun", ipa: "ˈlaɪbrəri", vi: "thư viện", eng: "A building containing collections of books.", icon: "🏛️" },
    { word: "park", cat: "noun", ipa: "pɑːrk", vi: "công viên", eng: "A large public green area in a town.", icon: "🌲" },
    { word: "restaurant", cat: "noun", ipa: "ˈrestrɒnt", vi: "nhà hàng", eng: "A place where people pay to sit and eat meals.", icon: "🍽️" },
    { word: "school", cat: "noun", ipa: "skuːl", vi: "trường học", eng: "An institution for educating children.", icon: "🏫" },
    { word: "supermarket", cat: "noun", ipa: "ˈsuːpərmɑːrkɪt", vi: "siêu thị", eng: "A large self-service shop selling foods and goods.", icon: "🛒" },
    { word: "cinema", cat: "noun", ipa: "ˈsɪnəmə", vi: "rạp chiếu phim", eng: "A theater where movies are shown.", icon: "🍿" },
    { word: "museum", cat: "noun", ipa: "mjuˈziːəm", vi: "bảo tàng", eng: "A building in which objects of historical, scientific, or cultural interest are stored.", icon: "🖼️" },
    { word: "hotel", cat: "noun", ipa: "hoʊˈtel", vi: "khách sạn", eng: "An establishment providing accommodations, meals.", icon: "🏨" },
    { word: "bank", cat: "noun", ipa: "bæŋk", vi: "ngân hàng", eng: "A financial establishment that invests money.", icon: "🏦" },
    { word: "bakery", cat: "noun", ipa: "ˈbeɪkəri", vi: "tiệm bánh", eng: "A place where bread and cakes are made or sold.", icon: "🥖" },
    { word: "cafe", cat: "noun", ipa: "kæˈfeɪ", vi: "quán cà phê", eng: "A small restaurant selling light meals and drinks.", icon: "☕" },
    { word: "stadium", cat: "noun", ipa: "ˈsteɪdiəm", vi: "sân vận động", eng: "A sports arena with tiers of seats.", icon: "🏟️" },
    { word: "bridge", cat: "noun", ipa: "brɪdʒ", vi: "cây cầu", eng: "A structure carrying a road over a river.", icon: "🌉" },
    { word: "sidewalk", cat: "noun", ipa: "ˈsaɪdwɔːk", vi: "vỉa hè", eng: "A paved path for pedestrians at the side of a road.", icon: "🛣️" },
    { word: "monument", cat: "noun", ipa: "ˈmɒnjumənt", vi: "tượng đài", eng: "A statue, building, or other structure erected to commemorate a notable person or event.", icon: "🗽" },
    // --- VERBS ---
    { word: "cross", cat: "verb", ipa: "krɒs", vi: "băng qua", eng: "To go across from one side to the other.", icon: "🚸" },
    { word: "explore", cat: "verb", ipa: "ɪkˈsplɔːr", vi: "khám phá", eng: "To travel around an area to learn about it.", icon: "🔭" },
    { word: "turn", cat: "verb", ipa: "tɜːrn", vi: "rẽ, quẹo", eng: "To change direction when walking or driving.", icon: "↩️" },
    { word: "walk", cat: "verb", ipa: "wɔːk", vi: "đi bộ", eng: "To move on foot at a normal speed.", icon: "🚶‍♂️" },
    { word: "go", cat: "verb", ipa: "ɡoʊ", vi: "đi", eng: "To move or travel to a place.", icon: "🏃" },
    { word: "pass", cat: "verb", ipa: "pæs", vi: "đi qua", eng: "To move past or through a place.", icon: "➡️" },
    { word: "find", cat: "verb", ipa: "faɪnd", vi: "tìm kiếm", eng: "To discover or perceive by chance or unexpectedly.", icon: "🔍" },
    { word: "look", cat: "verb", ipa: "lʊk", vi: "nhìn", eng: "To direct one's gaze toward someone or something.", icon: "👀" },
    { word: "visit", cat: "verb", ipa: "ˈvɪzɪt", vi: "thăm viếng", eng: "To go to see and spend time with someone or somewhere.", icon: "🗺️" },
    { word: "buy", cat: "verb", ipa: "baɪ", vi: "mua", eng: "To get something by paying money for it.", icon: "🛍️" },
    { word: "pay", cat: "verb", ipa: "peɪ", vi: "trả tiền", eng: "To give money for goods or services.", icon: "💵" },
    { word: "wait", cat: "verb", ipa: "weɪt", vi: "chờ đợi", eng: "To stay where one is or delay action until a particular time or event.", icon: "⏳" },
    { word: "stop", cat: "verb", ipa: "stɒp", vi: "dừng lại", eng: "To come to an end; cease to happen.", icon: "🛑" },
    { word: "drive", cat: "verb", ipa: "draɪv", vi: "lái xe", eng: "To operate and control the direction and speed of a motor vehicle.", icon: "🚗" },
    { word: "ride", cat: "verb", ipa: "raɪd", vi: "cưỡi, đạp xe", eng: "To sit on and control the movement of an animal or vehicle.", icon: "🚲" },
    { word: "park", cat: "verb", ipa: "pɑːrk", vi: "đỗ xe", eng: "To bring a vehicle that one is driving to a halt and leave it temporarily.", icon: "🅿️" },
    { word: "meet", cat: "verb", ipa: "miːt", vi: "gặp gỡ", eng: "To arrange or happen to come into the presence or company of someone.", icon: "🤝" },
    { word: "eat", cat: "verb", ipa: "iːt", vi: "ăn", eng: "To put food into the mouth and chew and swallow it.", icon: "🍔" },
    { word: "drink", cat: "verb", ipa: "drɪŋk", vi: "uống", eng: "To take a liquid into the mouth and swallow.", icon: "🥤" },
    { word: "ask", cat: "verb", ipa: "æsk", vi: "hỏi", eng: "To say something in order to obtain an answer or some information.", icon: "❓" },
    { word: "stay", cat: "verb", ipa: "steɪ", vi: "ở lại", eng: "To remain in the same place.", icon: "🏠" },
    { word: "live", cat: "verb", ipa: "lɪv", vi: "sống", eng: "To remain alive; to reside somewhere.", icon: "🌍" },
    { word: "work", cat: "verb", ipa: "wɜːrk", vi: "làm việc", eng: "To perform activity in order to achieve a purpose.", icon: "💼" },
    { word: "open", cat: "verb", ipa: "ˈoʊpən", vi: "mở cửa", eng: "To move so as to leave a space allowing access and view.", icon: "🔓" },
    { word: "close", cat: "verb", ipa: "kloʊz", vi: "đóng cửa", eng: "To block up an opening; to shut.", icon: "🔒" },
    { word: "enter", cat: "verb", ipa: "ˈentər", vi: "đi vào", eng: "To come or go into a place.", icon: "🚪" },
    { word: "leave", cat: "verb", ipa: "liːv", vi: "rời khỏi", eng: "To go away from.", icon: "👋" },
    { word: "arrive", cat: "verb", ipa: "əˈraɪv", vi: "đến nơi", eng: "To reach a place at the end of a journey.", icon: "🏁" },
    { word: "depart", cat: "verb", ipa: "dɪˈpɑːrt", vi: "khởi hành", eng: "To leave, typically in order to start a journey.", icon: "🛫" },
    { word: "travel", cat: "verb", ipa: "ˈtrævl", vi: "du lịch", eng: "To make a journey, typically of some length.", icon: "🧳" },
    // --- ADJECTIVES ---
    { word: "crowded", cat: "adj", ipa: "ˈkraʊdɪd", vi: "đông đúc", eng: "Full of people, with little space.", icon: "👥" },
    { word: "narrow", cat: "adj", ipa: "ˈnæroʊ", vi: "hẹp, chật", eng: "Small in width, not wide.", icon: "↕️" },
    { word: "busy", cat: "adj", ipa: "ˈbɪzi", vi: "nhộn nhịp, bận rộn", eng: "Full of activity and people.", icon: "🔊" },
    { word: "nearby", cat: "adj", ipa: "ˌnɪrˈbaɪ", vi: "gần đây", eng: "Not far away, close in distance.", icon: "📍" },
    { word: "famous", cat: "adj", ipa: "ˈfeɪməs", vi: "nổi tiếng", eng: "Known about by many people.", icon: "⭐" },
    { word: "quiet", cat: "adj", ipa: "ˈkwaɪət", vi: "yên tĩnh", eng: "Making little or no noise.", icon: "🤫" },
    { word: "clean", cat: "adj", ipa: "kliːn", vi: "sạch sẽ", eng: "Free from dirt, marks, or stains.", icon: "✨" },
    { word: "dirty", cat: "adj", ipa: "ˈdɜːrti", vi: "dơ bẩn", eng: "Covered or marked with an unclean substance.", icon: "🗑️" },
    { word: "big", cat: "adj", ipa: "bɪɡ", vi: "to lớn", eng: "Of considerable size or extent.", icon: "🐘" },
    { word: "small", cat: "adj", ipa: "smɔːl", vi: "nhỏ bé", eng: "Of a size that is less than normal or usual.", icon: "🐁" },
    { word: "old", cat: "adj", ipa: "oʊld", vi: "cũ, già", eng: "Having lived for a long time; no longer young.", icon: "🏛️" },
    { word: "new", cat: "adj", ipa: "njuː", vi: "mới", eng: "Not existing before; made, introduced, or discovered recently.", icon: "🆕" },
    { word: "modern", cat: "adj", ipa: "ˈmɒdərn", vi: "hiện đại", eng: "Relating to the present or recent times.", icon: "🏙️" },
    { word: "historic", cat: "adj", ipa: "hɪˈstɒrɪk", vi: "mang tính lịch sử", eng: "Famous or important in history.", icon: "📜" },
    { word: "expensive", cat: "adj", ipa: "ɪkˈspensɪv", vi: "đắt đỏ", eng: "Costing a lot of money.", icon: "💎" },
    { word: "cheap", cat: "adj", ipa: "tʃiːp", vi: "rẻ", eng: "Costing very little; relatively low in price.", icon: "🏷️" },
    { word: "popular", cat: "adj", ipa: "ˈpɒpjələr", vi: "phổ biến", eng: "Liked, admired, or enjoyed by many people.", icon: "👍" },
    { word: "safe", cat: "adj", ipa: "seɪf", vi: "an toàn", eng: "Protected from or not exposed to danger or risk.", icon: "🛡️" },
    { word: "dangerous", cat: "adj", ipa: "ˈdeɪndʒərəs", vi: "nguy hiểm", eng: "Able or likely to cause harm or injury.", icon: "⚠️" },
    { word: "empty", cat: "adj", ipa: "ˈempti", vi: "trống rỗng", eng: "Containing nothing; not filled or occupied.", icon: "🕳️" },
    { word: "friendly", cat: "adj", ipa: "ˈfrendli", vi: "thân thiện", eng: "Kind and pleasant.", icon: "😊" },
    { word: "local", cat: "adj", ipa: "ˈloʊkl", vi: "địa phương", eng: "Belonging or relating to a particular area or neighborhood.", icon: "🏘️" },
    { word: "public", cat: "adj", ipa: "ˈpʌblɪk", vi: "công cộng", eng: "Of or concerning the people as a whole.", icon: "📢" },
    { word: "private", cat: "adj", ipa: "ˈpraɪvət", vi: "riêng tư", eng: "Belonging to or for the use of one particular person or group.", icon: "🚫" },
    { word: "tall", cat: "adj", ipa: "tɔːl", vi: "cao", eng: "Of great or more than average height.", icon: "🏢" },
    { word: "short", cat: "adj", ipa: "ʃɔːrt", vi: "ngắn, thấp", eng: "Measuring a small distance from end to end.", icon: "📏" },
    { word: "far", cat: "adj", ipa: "fɑːr", vi: "xa (tính từ)", eng: "At, to, or by a great distance.", icon: "🔭" },
    { word: "interesting", cat: "adj", ipa: "ˈɪntrəstɪŋ", vi: "thú vị", eng: "Arousing curiosity or interest.", icon: "🤩" },
    { word: "beautiful", cat: "adj", ipa: "ˈbjuːtɪfl", vi: "đẹp", eng: "Pleasing the senses or mind aesthetically.", icon: "🌸" },
    { word: "ugly", cat: "adj", ipa: "ˈʌɡli", vi: "xấu xí", eng: "Unpleasant or repulsive.", icon: "🤢" },
    // --- ADVERBS ---
    { word: "straight", cat: "adv", ipa: "streɪt", vi: "thẳng", eng: "In a direct line, without turning.", icon: "⬆️" },
    { word: "ahead", cat: "adv", ipa: "əˈhed", vi: "phía trước", eng: "Further forward in space or time.", icon: "⏩" },
    { word: "quickly", cat: "adv", ipa: "ˈkwɪkli", vi: "nhanh chóng", eng: "At a fast speed.", icon: "⚡" },
    { word: "carefully", cat: "adv", ipa: "ˈkerˌfʊli", vi: "cẩn thận", eng: "With great attention and care.", icon: "🛡️" },
    { word: "here", cat: "adv", ipa: "hɪr", vi: "ở đây", eng: "In, at, or to this place or position.", icon: "👇" },
    { word: "there", cat: "adv", ipa: "ðer", vi: "ở đó", eng: "In, at, or to that place or position.", icon: "👉" },
    { word: "near", cat: "adv", ipa: "nɪr", vi: "gần", eng: "At or to a short distance away.", icon: "📍" },
    { word: "far", cat: "adv", ipa: "fɑːr", vi: "xa (trạng từ)", eng: "At, to, or by a great distance.", icon: "🔭" },
    { word: "away", cat: "adv", ipa: "əˈweɪ", vi: "đi xa", eng: "To or at a distance from a particular place.", icon: "🏃" },
    { word: "back", cat: "adv", ipa: "bæk", vi: "trở lại", eng: "In, to, or towards an original place or condition.", icon: "🔙" },
    { word: "around", cat: "adv", ipa: "əˈraʊnd", vi: "xung quanh", eng: "Located or situated on every side.", icon: "🔄" },
    { word: "out", cat: "adv", ipa: "aʊt", vi: "bên ngoài", eng: "Moving or appearing to move away from a particular place.", icon: "🚪" },
    { word: "in", cat: "adv", ipa: "ɪn", vi: "bên trong", eng: "Expressing movement with the result that someone or something becomes enclosed.", icon: "📥" },
    { word: "up", cat: "adv", ipa: "ʌp", vi: "lên trên", eng: "Toward a higher place or position.", icon: "👆" },
    { word: "down", cat: "adv", ipa: "daʊn", vi: "xuống dưới", eng: "Toward or in a lower place or position.", icon: "👇" },
    { word: "left", cat: "adv", ipa: "left", vi: "bên trái", eng: "On or toward the left side.", icon: "⬅️" },
    { word: "right", cat: "adv", ipa: "raɪt", vi: "bên phải", eng: "On or toward the right side.", icon: "➡️" },
    { word: "safely", cat: "adv", ipa: "ˈseɪfli", vi: "an toàn", eng: "In a way that gives protection from danger.", icon: "🦺" },
    { word: "slowly", cat: "adv", ipa: "ˈsloʊli", vi: "chậm chạp", eng: "At a slow speed; not quickly.", icon: "🐢" },
    { word: "fast", cat: "adv", ipa: "fæst", vi: "nhanh", eng: "At high speed.", icon: "🏎️" },
    { word: "early", cat: "adv", ipa: "ˈɜːrli", vi: "sớm", eng: "Happening or done before the usual or expected time.", icon: "🌅" },
    { word: "late", cat: "adv", ipa: "leɪt", vi: "trễ", eng: "Doing something or taking place after the expected time.", icon: "🌃" },
    { word: "always", cat: "adv", ipa: "ˈɔːlweɪz", vi: "luôn luôn", eng: "At all times; on all occasions.", icon: "💯" },
    { word: "usually", cat: "adv", ipa: "ˈjuːʒəli", vi: "thường xuyên", eng: "Under normal conditions; generally.", icon: "🔄" },
    { word: "often", cat: "adv", ipa: "ˈɒfn", vi: "thường", eng: "Frequently; many times.", icon: "🔁" },
    { word: "sometimes", cat: "adv", ipa: "ˈsʌmtaɪmz", vi: "thỉnh thoảng", eng: "Occasionally, rather than all of the time.", icon: "🔀" },
    { word: "rarely", cat: "adv", ipa: "ˈrerli", vi: "hiếm khi", eng: "Not often; seldom.", icon: "📉" },
    { word: "never", cat: "adv", ipa: "ˈnevər", vi: "không bao giờ", eng: "At no time in the past or future.", icon: "❌" },
    // --- PREPOSITIONS ---
    { word: "opposite", cat: "prep", ipa: "ˈɒpəzɪt", vi: "đối diện", eng: "In a position facing someone or something.", icon: "↔️" },
    { word: "next to", cat: "prep", ipa: "nekst tə", vi: "kế bên", eng: "In a position right beside something.", icon: "👉" },
    { word: "between", cat: "prep", ipa: "bɪˈtwiːn", vi: "ở giữa", eng: "In or into the space separating two things.", icon: "⬌" },
    { word: "along", cat: "prep", ipa: "əˈlɒŋ", vi: "dọc theo", eng: "Moving in a constant direction on a path.", icon: "🔜" },
    { word: "across", cat: "prep", ipa: "əˈkrɒs", vi: "ngang qua, bên kia", eng: "From one side to the other side of.", icon: "🔀" },
    { word: "in", cat: "prep", ipa: "ɪn", vi: "trong", eng: "Expressing the situation of something that is or appears to be enclosed.", icon: "📦" },
    { word: "on", cat: "prep", ipa: "ɒn", vi: "trên", eng: "Physically in contact with and supported by a surface.", icon: "🔛" },
    { word: "at", cat: "prep", ipa: "æt", vi: "tại", eng: "Expressing location or arrival in a particular place.", icon: "🎯" },
    { word: "by", cat: "prep", ipa: "baɪ", vi: "gần, bởi", eng: "Identifying the agent performing an action; near.", icon: "🤝" },
    { word: "under", cat: "prep", ipa: "ˈʌndər", vi: "dưới", eng: "Extending or directly below something.", icon: "🔽" },
    { word: "over", cat: "prep", ipa: "ˈoʊvər", vi: "qua, phía trên", eng: "Extending directly upwards from.", icon: "⤴️" },
    { word: "behind", cat: "prep", ipa: "bɪˈhaɪnd", vi: "phía sau", eng: "At or to the far side of something.", icon: "🔙" },
    { word: "in front of", cat: "prep", ipa: "ɪn frʌnt əv", vi: "phía trước", eng: "In a position just ahead or at the front part of someone or something.", icon: "⏩" },
    { word: "near", cat: "prep", ipa: "nɪr", vi: "gần", eng: "At or to a short distance away.", icon: "📍" },
    { word: "past", cat: "prep", ipa: "pæst", vi: "đi qua", eng: "To or on the further side of.", icon: "⏭️" },
    { word: "through", cat: "prep", ipa: "θruː", vi: "xuyên qua", eng: "Moving in one side and out of the other side of.", icon: "🕳️" },
    { word: "into", cat: "prep", ipa: "ˈɪntuː", vi: "vào trong", eng: "Expressing movement or action with the result that someone or something becomes enclosed.", icon: "📥" },
    { word: "out of", cat: "prep", ipa: "aʊt əv", vi: "ra khỏi", eng: "Moving from inside to outside.", icon: "📤" },
    { word: "onto", cat: "prep", ipa: "ˈɒntuː", vi: "lên trên", eng: "Moving to a location on the surface of.", icon: "🆙" },
    { word: "off", cat: "prep", ipa: "ɒf", vi: "rời khỏi bề mặt", eng: "Moving away and often down from.", icon: "📴" },
    { word: "towards", cat: "prep", ipa: "təˈwɔːrdz", vi: "về hướng", eng: "In the direction of.", icon: "🎯" },
    { word: "up", cat: "prep", ipa: "ʌp", vi: "lên", eng: "From a lower to a higher point.", icon: "⬆️" },
    { word: "down", cat: "prep", ipa: "daʊn", vi: "xuống", eng: "From a higher to a lower point.", icon: "⬇️" },
    { word: "around", cat: "prep", ipa: "əˈraʊnd", vi: "vòng quanh", eng: "On every side of.", icon: "🔄" },
    { word: "from", cat: "prep", ipa: "frɒm", vi: "từ", eng: "Indicating the point in space at which a journey, motion, or action starts.", icon: "🛫" },
    { word: "to", cat: "prep", ipa: "tuː", vi: "đến", eng: "Expressing motion in the direction of.", icon: "🛬" },
    { word: "with", cat: "prep", ipa: "wɪð", vi: "với", eng: "Accompanied by.", icon: "🤝" },
    { word: "without", cat: "prep", ipa: "wɪˈðaʊt", vi: "không có", eng: "In the absence of.", icon: "🚫" },
    { word: "about", cat: "prep", ipa: "əˈbaʊt", vi: "về", eng: "On the subject of; concerning.", icon: "ℹ️" },
    // --- DETERMINERS ---
    { word: "the", cat: "det", ipa: "ðə", vi: "(mạo từ xác định)", eng: "Used before a noun to refer to a specific thing.", icon: "📌" },
    { word: "a / an", cat: "det", ipa: "ə / æn", vi: "một (không xác định)", eng: "Used before a noun to refer to one unspecific thing.", icon: "1️⃣" },
    { word: "every", cat: "det", ipa: "ˈevri", vi: "mỗi, mọi", eng: "Used to refer to all members of a group.", icon: "🔁" },
    { word: "this", cat: "det", ipa: "ðɪs", vi: "này, đây", eng: "Used to identify a specific person or thing close by.", icon: "👇" },
    { word: "that", cat: "det", ipa: "ðæt", vi: "đó, kia", eng: "Used to identify a specific person or thing observed or heard by the speaker.", icon: "👉" },
    { word: "these", cat: "det", ipa: "ðiːz", vi: "những cái này", eng: "Plural form of this.", icon: "👇" },
    { word: "those", cat: "det", ipa: "ðoʊz", vi: "những cái đó", eng: "Plural form of that.", icon: "👉" },
    { word: "my", cat: "det", ipa: "maɪ", vi: "của tôi", eng: "Belonging to or associated with the speaker.", icon: "🙋" },
    { word: "your", cat: "det", ipa: "jʊr", vi: "của bạn", eng: "Belonging to or associated with the person or people that the speaker is addressing.", icon: "🫵" },
    { word: "his", cat: "det", ipa: "hɪz", vi: "của anh ấy", eng: "Belonging to or associated with a male person previously mentioned.", icon: "👨" },
    { word: "her", cat: "det", ipa: "hɜːr", vi: "của cô ấy", eng: "Belonging to or associated with a female person previously mentioned.", icon: "👩" },
    { word: "its", cat: "det", ipa: "ɪts", vi: "của nó", eng: "Belonging to or associated with a thing previously mentioned.", icon: "🐾" },
    { word: "our", cat: "det", ipa: "ˈaʊər", vi: "của chúng ta", eng: "Belonging to or associated with the speaker and one or more other people.", icon: "👪" },
    { word: "their", cat: "det", ipa: "ðer", vi: "của họ", eng: "Belonging to or associated with the people or things previously mentioned.", icon: "👥" },
    { word: "some", cat: "det", ipa: "sʌm", vi: "một vài", eng: "An unspecified amount or number of.", icon: "⚖️" },
    { word: "any", cat: "det", ipa: "ˈeni", vi: "bất kỳ", eng: "Used to refer to one or some of a thing or number of things.", icon: "❓" },
    { word: "many", cat: "det", ipa: "ˈmeni", vi: "nhiều (đếm được)", eng: "A large number of.", icon: "💯" },
    { word: "much", cat: "det", ipa: "mʌtʃ", vi: "nhiều (không đếm được)", eng: "A large amount of.", icon: "🌊" },
    { word: "all", cat: "det", ipa: "ɔːl", vi: "tất cả", eng: "The whole quantity or extent of a particular group or thing.", icon: "🌌" },
    { word: "both", cat: "det", ipa: "boʊθ", vi: "cả hai", eng: "Used to refer to two people or things.", icon: "✌️" },
    // --- PRONOUNS ---
    { word: "it", cat: "pron", ipa: "ɪt", vi: "nó", eng: "Used to refer to a thing previously mentioned.", icon: "👆" },
    { word: "we", cat: "pron", ipa: "wiː", vi: "chúng ta", eng: "Used to refer to the speaker and one or more others.", icon: "👫" },
    { word: "you", cat: "pron", ipa: "juː", vi: "bạn, các bạn", eng: "Used to refer to the person being addressed.", icon: "🫵" },
    { word: "I", cat: "pron", ipa: "aɪ", vi: "tôi", eng: "Used by a speaker to refer to himself or herself.", icon: "🙋‍♂️" },
    { word: "he", cat: "pron", ipa: "hiː", vi: "anh ấy", eng: "Used to refer to a man, boy, or male animal.", icon: "👨" },
    { word: "she", cat: "pron", ipa: "ʃiː", vi: "cô ấy", eng: "Used to refer to a woman, girl, or female animal.", icon: "👩" },
    { word: "they", cat: "pron", ipa: "ðeɪ", vi: "họ, chúng", eng: "Used to refer to two or more people or things.", icon: "👥" },
    { word: "me", cat: "pron", ipa: "miː", vi: "tôi (tân ngữ)", eng: "Used by a speaker to refer to himself or herself as the object of a verb or preposition.", icon: "🙋" },
    { word: "him", cat: "pron", ipa: "hɪm", vi: "anh ấy (tân ngữ)", eng: "Used as the object of a verb or preposition to refer to a male person.", icon: "👨" },
    { word: "her", cat: "pron", ipa: "hɜːr", vi: "cô ấy (tân ngữ)", eng: "Used as the object of a verb or preposition to refer to a female person.", icon: "👩" },
    { word: "us", cat: "pron", ipa: "ʌs", vi: "chúng ta (tân ngữ)", eng: "Used by a speaker to refer to himself or herself and one or more other people as the object of a verb.", icon: "👪" },
    { word: "them", cat: "pron", ipa: "ðem", vi: "họ (tân ngữ)", eng: "Used as the object of a verb or preposition to refer to two or more people.", icon: "👥" },
    { word: "someone", cat: "pron", ipa: "ˈsʌmwʌn", vi: "ai đó", eng: "An unknown or unspecified person.", icon: "👤" },
    { word: "anyone", cat: "pron", ipa: "ˈeniwʌn", vi: "bất kỳ ai", eng: "Any person or people.", icon: "❓" },
    { word: "everyone", cat: "pron", ipa: "ˈevriwʌn", vi: "mọi người", eng: "Every person.", icon: "🌍" },
    { word: "no one", cat: "pron", ipa: "ˈnoʊ wʌn", vi: "không ai", eng: "No person; not a single person.", icon: "🚫" },
    { word: "something", cat: "pron", ipa: "ˈsʌmθɪŋ", vi: "thứ gì đó", eng: "A thing that is unspecified or unknown.", icon: "📦" },
    { word: "anything", cat: "pron", ipa: "ˈeniθɪŋ", vi: "bất kỳ thứ gì", eng: "Used to refer to a thing, no matter what.", icon: "❓" },
    { word: "everything", cat: "pron", ipa: "ˈevriθɪŋ", vi: "mọi thứ", eng: "All things.", icon: "🌌" },
    { word: "nothing", cat: "pron", ipa: "ˈnʌθɪŋ", vi: "không gì cả", eng: "Not anything; no single thing.", icon: "🕳️" },
    { word: "which", cat: "pron", ipa: "wɪtʃ", vi: "cái nào", eng: "Asking for information specifying one or more people or things from a definite set.", icon: "🤷" },
    { word: "who", cat: "pron", ipa: "huː", vi: "ai", eng: "What or which person or people.", icon: "❓" },
    { word: "where", cat: "pron", ipa: "wer", vi: "ở đâu", eng: "In or to what place or position.", icon: "🗺️" },
    // --- CONJUNCTIONS ---
    { word: "and", cat: "conj", ipa: "ænd", vi: "và", eng: "Used to connect words, phrases, or clauses.", icon: "➕" },
    { word: "then", cat: "conj", ipa: "ðen", vi: "sau đó, rồi", eng: "After that, next in order.", icon: "⏭️" },
    { word: "because", cat: "conj", ipa: "bɪˈkɒz", vi: "bởi vì", eng: "For the reason that.", icon: "💡" },
    { word: "but", cat: "conj", ipa: "bʌt", vi: "nhưng", eng: "Used to introduce a phrase or clause contrasting with what has already been mentioned.", icon: "🛑" },
    { word: "or", cat: "conj", ipa: "ɔːr", vi: "hoặc", eng: "Used to link alternatives.", icon: "🔄" },
    { word: "so", cat: "conj", ipa: "soʊ", vi: "vì vậy", eng: "And for this reason; therefore.", icon: "👉" },
    { word: "although", cat: "conj", ipa: "ɔːlˈðoʊ", vi: "mặc dù", eng: "In spite of the fact that; even though.", icon: "⚖️" },
    { word: "if", cat: "conj", ipa: "ɪf", vi: "nếu", eng: "Introducing a conditional clause.", icon: "❓" },
    { word: "unless", cat: "conj", ipa: "ənˈles", vi: "trừ khi", eng: "Except if.", icon: "🚫" },
    { word: "while", cat: "conj", ipa: "waɪl", vi: "trong khi", eng: "During the time that; at the same time as.", icon: "⏳" },
    { word: "when", cat: "conj", ipa: "wen", vi: "khi", eng: "At or on which.", icon: "⏱️" },
    { word: "as", cat: "conj", ipa: "æz", vi: "khi, vì", eng: "Used to indicate that something happens during the time when something else is taking place.", icon: "🔄" },
    { word: "since", cat: "conj", ipa: "sɪns", vi: "từ khi, vì", eng: "For the reason that; because.", icon: "🕰️" },
    { word: "until", cat: "conj", ipa: "ənˈtɪl", vi: "cho đến khi", eng: "Up to.", icon: "🛑" },
    { word: "before", cat: "conj", ipa: "bɪˈfɔːr", vi: "trước khi", eng: "During the period of time preceding a particular event or time.", icon: "⏪" },
    { word: "after", cat: "conj", ipa: "ˈæftər", vi: "sau khi", eng: "In the time following.", icon: "⏩" },
    { word: "whether", cat: "conj", ipa: "ˈweðər", vi: "liệu", eng: "Expressing a doubt or choice between alternatives.", icon: "🤷" },
    { word: "yet", cat: "conj", ipa: "jet", vi: "tuy nhiên", eng: "But at the same time; but nevertheless.", icon: "🤔" }
];`;

content = content.replace(/const allVocab = \[\s*\/\/ --- NOUNS ---[\s\S]*?\];/, newVocab);

// Let's also update the vocab count displayed in the HTML
content = content.replace(/<span style="color:var\(--text-muted\);font-weight:400;font-size:0.85rem" id="vocabCount">\(42 từ\)<\/span>/, 
    '<span style="color:var(--text-muted);font-weight:400;font-size:0.85rem" id="vocabCount">(195 từ)</span>');

// Also update the flashcard count
content = content.replace(/<span class="info-tag progress" id="fcProgress">1 \/ 42<\/span>/,
    '<span class="info-tag progress" id="fcProgress">1 / 195</span>');

fs.writeFileSync(file, content);
console.log('Update complete. Total words added.');
